# .github/workflows/ci.yml
name: CI Pipeline (Lint & Build Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run flake8
        run: flake8 .

  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image (no push)
        # 此步骤将验证 Dockerfile 是否能工作
        # 如果 'models/' 目录或 'src/' 目录中的文件丢失，此步骤将失败
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false # 不推送
          tags: local-build:test